---
kind: pipeline
type: docker
name: devopsTools

steps:
- name: build_debian
  when:
    branch: main
  image: plugins/docker
  build_args:
    MYTAG: 0.2
  settings:
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: redbeard28/debian-workspace
    tags: ${MYTAG}
    context: "debian-slim-workspace"
    dockerfile: "debian-slim-workspace/Dockerfile"
- name: build_base
  when:
    branch: main
  image: plugins/docker
  build_args:
    MYTAG: 0.2
  settings:
    username:
      from-from_secret: DOCKERHUB_USER
    password:
      from-from_secret: DOCKERHUB_PASSWORD
    repo: redbeard28/base-devspace
    tags: ${MYTAG}
    context: "base-devspace"
    dockerfile: "base-devspace/Dockerfile"
#  build:
#    command:
#      - >
#        pwd
#        ls -l
#        TOKEN=$( curl -sSLd "username=${DOCKERHUB_USER}&password=${DOCKERHUB_PASSWORD}" https://hub.docker.com/v2/users/login | jq -r ".token" )
#        STATUS=$( curl -sH "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/${DOCKER_REPO}/tags/${MYTAG}/" | jq -r ".tag_status" )
#        echo $STATUS
#        if [ $STATUS == "active" ]; then
#
#          echo "#######@ NOTHING TO DO #####"
#          exit 0
#        fi
#        if [ "${CIRCLE_BRANCH}" == "main" ]; then
#          cd debian-workspace
#          docker build -t ${DOCKER_REPO}:$MYTAG .
#          if [ $? == 0 ];then
#            echo $DOCKERHUB_PASSWORD | docker login -u ${DOCKERHUB_USER} --password-stdin
#            docker push ${DOCKER_REPO}:$MYTAG
#          fi
#        fi
#      - >
#        TOKEN=$( curl -sSLd "username=${DOCKERHUB_USER}&password=${DOCKERHUB_PASSWORD}" https://hub.docker.com/v2/users/login | jq -r ".token" )
#        STATUS=$( curl -sH "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/${DOCKER_REPO}/tags/${MYTAG}/" | jq -r ".tag_status" )
#        echo $STATUS
#        if [ $STATUS == "active" ]; then
#          echo "#######@ NOTHING TO DO #####"
#          exit 0
#        fi
#        if [ "${CIRCLE_BRANCH}" == "main" ]; then
#          cd kubespray-workspace
#          docker build -t ${DOCKER_REPO}:$MYTAG .
#          if [ $? == 0 ];then
#            echo $DOCKERHUB_PASSWORD | docker login -u ${DOCKERHUB_USER} --password-stdin
#            docker push ${DOCKER_REPO}:$MYTAG
#          fi
#        fi


