version: 2.1

jobs:
#  build:
#    docker:
#      # specify the version
#      - image: cimg/base:2022.11
#        auth:
#          username: $DOCKERHUB_USER
#          password: $DOCKERHUB_PASSWORD
#    steps:
#      - checkout
#      - setup_remote_docker
#
#      - run:
#          name: Push application Docker image
#          environment:
#            DOCKER_REPO: redbeard28/codeserver-workspace:0.2
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "main" ]; then
#              cd codeserver-workspace
#              docker build -t ${DOCKER_REPO} .
#              echo "Avant Login"
#              echo $DOCKERHUB_PASSWORD | docker login -u ${DOCKERHUB_USER} --password-stdin
#              echo "Avant push docker hub"
#              docker push ${DOCKER_REPO}
#            fi


  build_codeserver:
    working_directory: ~/codeserver-workspace
    docker:
      - image: cimg/base:2022.11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/codeserver-workspace
      - setup_remote_docker
      - run:
          name: Build application Docker image
          environment:
            MYTAG: 0.2
            DOCKER_REPO: redbeard28/codeserver-workspace
          command: |
            TOKEN=$( curl -sSLd "username=${DOCKERHUB_USER}&password=${DOCKERHUB_PASSWORD}" https://hub.docker.com/v2/users/login | jq -r ".token" )
            STATUS=$( curl -sH "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/${DOCKER_REPO}/tags/${MYTAG}/" | jq -r ".tag_status" )
            echo $STATUS
            if [ $STATUS == "active" ]; then
              
              echo "#######@ NOTHING TO DO #####"
              exit 0
            else
              if [ "${CIRCLE_BRANCH}" == "main" ]; then
                cd codeserver-workspace
                docker build -t ${DOCKER_REPO}:$MYTAG .
              fi
            fi



  deploy_codeserver:
    working_directory: ~/codeserver-workspace
    docker:
      - image: cimg/base:2022.11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/codeserver-workspace
      - setup_remote_docker
      - run:
          name: Deploy application Docker image
          environment:
            MYTAG: 0.2
            DOCKER_REPO: redbeard28/codeserver-workspace
          command: |
            TOKEN=$( curl -sSLd "username=${DOCKERHUB_USER}&password=${DOCKERHUB_PASSWORD}" https://hub.docker.com/v2/users/login | jq -r ".token" )
            STATUS=$( curl -sH "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/${DOCKER_REPO}/tags/${MYTAG}/" | jq -r ".tag_status" )
            echo $STATUS
            if [ $STATUS == "active" ]; then
              
              echo "#######@ NOTHING TO DO #####"
              exit 0
            else
              if [ "${CIRCLE_BRANCH}" == "main" ]; then
                echo $DOCKERHUB_PASSWORD | docker login -u ${DOCKERHUB_USER} --password-stdin
                docker push ${DOCKER_REPO}:$MYTAG
              fi
            fi


workflows:
  version: 2
  build_codeserver_and_deploy_codeserver:
    jobs:
      - build_codeserver:
          filters:
            branches:
              only: main
      - deploy_codeserver:
          requires:
            - build_codeserver
          filters:
            branches:
              only: main