version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/base:2022.11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker

      - deploy:
          name: Push application Docker image
          environment:
            DOCKER_REPO: redbeard28/codeserver-workspace:0.2
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              cd codeserver-workspace
              docker build -t ${DOCKER_REPO} .
              echo "Avant Login"
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} https://index.docker.io/v1/ 
              echo "Avant push docker hub"
              docker push ${DOCKER_REPO}
            fi