edit_uri: ''
extra:
  homepage: https://www.linkedin.com/in/jeremiecuadrado
  host_url: https://www.linkedin.com/in/jeremiecuadrado
extra_css:
- stylesheets/extra.css
- stylesheets/quickstart.css
extra_javascript:
- javascripts/config.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
nav:
- Home: README.md
- Make my docs: pages/mydocs.md
- Admin: pages/admin.md
- About: about.md
- Docs: https://github.com/redbeard28
plugins:
- macros:
    module_name: macros/helpers
repo_url: https://github.com/redbeard28
site_name: Kuma Labs Consulting workspace
site_url: #
theme:
  custom_dir: overrides
  favicon: assets/white_icon_transparent_background.png
  features:
  - navigation.instant
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  logo: assets/white_icon_transparent_background.png
  name: material
  palette:
  - scheme: workspace
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: workspace-dark
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
